# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Ascure-app"
client_id = "df1a5ac4600d89a813e59e066501a0a2"
application_url = "https://ave-pdf-circles-projectors.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ave-pdf-circles-projectors.trycloudflare.com/auth/callback",
  "https://ave-pdf-circles-projectors.trycloudflare.com/auth/shopify/callback",
  "https://ave-pdf-circles-projectors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "iskchase.myshopify.com"
